station_id = 'QAS_L'
nodata     = ['-999', 'NAN'] # if one is a string, all must be strings

['QAS_L_2021_raw_transmitted.txt']
format     = 'TX'
skiprows = 0
latitude = 61.03
longitude = 46.85
hygroclip_t_offset = 40
dsr_eng_coef = 13.28
usr_eng_coef = 11.64
dlr_eng_coef = 10.8
ulr_eng_coef = 10.11
pt_z_coef = 0.4425
pt_z_p_coef = 1012
pt_z_factor = 2.5
pt_antifreeze = 50
boom_azimuth = 0
columns = ['time','rec','p','t_1','t_2','rh','wspd','wdir','dsr',
 'usr','dlr','ulr','t_rad','z_boom','z_stake','z_pt',
 't_i_1','t_i_2','t_i_3','t_i_4','t_i_5','t_i_6','t_i_7',
 't_i_8','tilt_x','tilt_y','gps_time','gps_lat','gps_lon',
 'gps_alt','gps_hdop','fan_dc','batt_v']



