station_id = 'QAS_M'
nodata     = ['-999', 'NAN'] # if one is a string, all must be strings

['QAS_M_2021_raw_transmitted.txt']
format     = 'TX'
skiprows = 0
latitude = 61.1
longitude = 46.83
hygroclip_t_offset = 0
dsr_eng_coef = 14.1
usr_eng_coef = 14.32
dlr_eng_coef = 10.55
ulr_eng_coef = 11.71
pt_z_coef = 0.4069
pt_z_p_coef = 1023.6
pt_z_factor = 2.5
pt_antifreeze = 50
boom_azimuth = 0
columns = ['time','rec','p','t_1','t_2','rh','wspd','wdir','dsr',
 'usr','dlr','ulr','t_rad','z_boom','z_stake','z_pt',
 't_i_1','t_i_2','t_i_3','t_i_4','t_i_5','t_i_6','t_i_7',
 't_i_8','tilt_x','tilt_y','gps_time','gps_lat','gps_lon',
 'gps_alt','gps_hdop','fan_dc','batt_v']


