[aws_operational]
l0_tx_uid_path = "/Users/maclu/work/pypromice/credentials/last_aws_uid.ini"
l0_repository_path = "/Users/maclu/data/aws-l0"
l0_repository_branch = "test/new_operation_script"
l3_repository_path = "/Users/maclu/data/aws-l3"
promice_data_issues = "/Users/maclu/data/PROMICE-AWS-data-issues"
bufr_output_path = "/Users/maclu/work/pypromice/scratch/tmp_output/bufr/"
status_path = "/Users/maclu/work/pypromice/scratch/tmp_output/status.csv"
max_processes = 4
aws_fileshare = "/Users/maclu/work/pypromice/scratch/tmp_output/fileshare/"

[aws]
server = "imap.gmail.com"
port = 993
account = "geus.aws@gmail.com"

[dmi]
server = "ftpserver.dmi.dk"
user = "0680dmi"

[logging]
log_file_path = "/Users/maclu/work/pypromice/scratch/tmp_output/aws_obs.log"
level = "info"
