on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: process_test
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"        
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: "main"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          python3 -m pip install --upgrade setuptools
          cd $GITHUB_WORKSPACE/main
          pip install .  
      - name: Clone AWS Level 0 data repo for testing
        env:
          GITLAB_TOKEN : ${{ secrets.GITLAB_TOKEN }}
        run: | 
          cd $GITHUB_WORKSPACE
          git clone --depth 1 https://oauth2:${{ env.GITLAB_TOKEN }}@geusgitlab.geus.dk/glaciology-and-climate/promice/aws-l0.git
      - name: Run data processing
        env:
          TEST_STATION: KPC_U CEN2 JAR
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/out/
          for i in $(echo ${{ env.TEST_STATION }} | tr ' ' '\n'); do
            python3 $GITHUB_WORKSPACE/main/src/pypromice/process/get_l3.py -v $GITHUB_WORKSPACE/main/src/pypromice/process/variables.csv -m $GITHUB_WORKSPACE/main/src/pypromice/process/metadata.csv -c $GITHUB_WORKSPACE/aws-l0/raw/config/$i.toml -i $GITHUB_WORKSPACE/aws-l0/raw -o $GITHUB_WORKSPACE/out/ -l 3
          done
      - name: Upload test output
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: out
